export default {
// GET UPDATE POLL
  GET_UPDATE_POLL: 'GET_UPDATE_POLL',

  // GET ALL POLLS FOR HOME PAGE
  GET_ALL_POLLS: 'GET_ALL_POLLS',
  GET_ALL_POLLS_START: 'GET_ALL_POLLS_START',
  GET_ALL_POLLS_ERROR: 'GET_ALL_POLLS_ERROR',

  // GET ALL USER'S POLLS
  GET_POLLS: 'GET_POLLS',
  GET_POLLS_START: 'GET_POLLS_START',
  GET_POLLS_ERROR: 'GET_POLLS_ERROR',

  GET_POLL_START: 'GET_POLL_START',
  GET_POLL: 'GET_POLL',
  GET_POLL_ERROR: 'GET_POLL_ERROR',

  POST_POLL: 'POST_POLL',
  POST_POLL_ERROR: 'POST_POLL_ERROR',

  UPDATE_POLL: 'UPDATE_POLL',
  UPDATE_POLL_ERROR: 'UPDATE_POLL_ERROR',

  DELETE_POLL: 'DELETE_POLL',
  DELETE_POLL_ERROR: 'DELETE_POLL_ERROR',

  // PARTICIPANT API
  GET_PARTICIPANTS: 'GET_PARTICIPANTS',
  POST_PARTICIPANT: 'POST_PARTICIPANT',
  DELETE_PARTICIPANT: 'DELETE_PARTICIPANT',

  // USERS
  POST_SIGNUP: 'POST_SIGNUP',
  POST_LOGIN: 'POST_LOGIN',
  POST_TOKEN_IS_VALID: 'POST_TOKEN_IS_VALID',
  POST_RESET_PASSWORD: 'POST_RESET_PASSWORD',

};
