export default {
  // GET ALL USER'S POLLS
  GET_POLLS: 'GET_POLLS',
  GET_POLLS_START: 'GET_POLLS_START',
  GET_POLLS_ERROR: 'GET_POLLS_ERROR',

  GET_POLL_START: 'GET_POLL_START',
  GET_POLL: 'GET_POLL',
  GET_POLL_ERROR: 'GET_POLL_ERROR',

  COPY_POLL: 'COPY_POLL',

  POST_POLL: 'POST_POLL',
  POST_POLL_ERROR: 'POST_POLL_ERROR',

  UPDATE_POLL: 'UPDATE_POLL',
  UPDATE_POLL_ERROR: 'UPDATE_POLL_ERROR',

  DELETE_POLL: 'DELETE_POLL',
  DELETE_POLL_ERROR: 'DELETE_POLL_ERROR',

  // PARTICIPANT API
  GET_PARTICIPANTS: 'GET_PARTICIPANTS',
  GET_PARTICIPANTS_ERROR: 'GET_PARTICIPANTS_ERROR',

  POST_PARTICIPANT: 'POST_PARTICIPANT',
  POST_PARTICIPANT_ERROR: 'POST_PARTICIPANT_ERROR',

  DELETE_PARTICIPANT: 'DELETE_PARTICIPANT',
  DELETE_PARTICIPANT_ERROR: 'DELETE_PARTICIPANT_ERROR',

  // USERS
  POST_SIGNUP: 'POST_SIGNUP',
  POST_SIGNUP_ERROR: 'POST_SIGNUP_ERROR',

  POST_LOGIN: 'POST_LOGIN',
  POST_LOGIN_START: 'POST_LOGIN_START',
  POST_LOGIN_ERROR: 'POST_LOGIN_ERROR',

  POST_TOKEN_IS_VALID: 'POST_TOKEN_IS_VALID',
  POST_TOKEN_IS_VALID_ERROR: 'POST_TOKEN_IS_VALID_ERROR',

  POST_RESET_PASSWORD: 'POST_RESET_PASSWORD',
  POST_RESET_PASSWORD_ERROR: 'POST_RESET_PASSWORD_ERROR',
};
