export const asyncTypes = {
// GET UPDATE POLL
  GET_UPDATE_POLL: 'GET_UPDATE_POLL',

  // POLL
  GET_POLL: 'GET_POLL',

  GET_ALL_POLLS: 'GET_ALL_POLLS',
  GET_ALL_POLLS_START: 'GET_ALL_POLLS_START',
  GET_ALL_POLLS_ERROR: 'GET_ALL_POLLS_ERROR',

  POST_POLL: 'POST_POLL',
  UPDATE_POLL: 'UPDATE_POLL',
  DELETE_POLL: 'DELETE_POLL',
  GET_POLLS: 'GET_POLLS',
  GET_PREVIEW_POLL: 'GET_PREVIEW_POLL',

  // PARTICIPANT API
  GET_PARTICIPANTS: 'GET_PARTICIPANTS',
  POST_PARTICIPANT: 'POST_PARTICIPANT',
  DELETE_PARTICIPANT: 'DELETE_PARTICIPANT',


  // USERS
  POST_SIGNUP: 'POST_SIGNUP',
  POST_LOGIN: 'POST_LOGIN',
  POST_TOKEN_IS_VALID: 'POST_TOKEN_IS_VALID',
  POST_RESET_PASSWORD: 'POST_RESET_PASSWORD',

};

/*
// GET UPDATE POLL
export const GET_UPDATE_POLL = 'GET_UPDATE_POLL';

// POLL
export const GET_POLL = 'GET_POLL';

export const GET_ALL_POLLS = 'GET_ALL_POLLS';
export const GET_ALL_POLLS_START = 'GET_ALL_POLLS_START';
export const GET_ALL_POLLS_ERROR = 'GET_ALL_POLLS_ERROR';


export const POST_POLL = 'POST_POLL';
export const UPDATE_POLL = 'UPDATE_POLL';
export const DELETE_POLL = 'DELETE_POLL';
export const GET_POLLS = 'GET_POLLS';
export const GET_PREVIEW_POLL = 'GET_PREVIEW_POLL';

// PARTICIPANT API
export const GET_PARTICIPANTS = 'GET_PARTICIPANTS';
export const POST_PARTICIPANT = 'POST_PARTICIPANT';
export const DELETE_PARTICIPANT = 'DELETE_PARTICIPANT';


// USERS
export const POST_SIGNUP = 'POST_SIGNUP';
export const POST_LOGIN = 'POST_LOGIN';
export const POST_TOKEN_IS_VALID = 'POST_TOKEN_IS_VALID';
export const POST_RESET_PASSWORD = 'POST_RESET_PASSWORD'; */
