// RADIO BUTTON CHANGE
export const syncTypes = {
  ANSWER_AUTO_CHANGE_TIME: 'ANSWER_AUTO_CHANGE_TIME',

  ANSWER_TIME: 'ANSWER_TIME',
  POLL_TIME: 'POLL_TIME',
  SHOW_TYPE: 'SHOW_TYPE',
  POLL_ACTIVE: 'POLL_ACTIVE',
  ANSWER_PERCENT: 'ANSWER_PERCENT',
  TYPE: 'TYPE',
  USER_DATA_COLLECT_TYPE: 'USER_DATA_COLLECT_TYPE',

  // ONCHANGES
  ON_CHANGE_NAME: 'ON_CHANGE_NAME',
  ON_CHANGE_DESC: 'ON_CHANGE_DESC',
  ON_CHANGE_LAST_DESC: 'ON_CHANGE_LAST_DESC',
  ON_CHANGE_QUESTION: 'ON_CHANGE_QUESTION',
  ON_CHANGE_QUESTION_DESC: 'ON_CHANGE_QUESTION_DESC',
  ON_CHANGE_ANSWER: 'ON_CHANGE_ANSWER',
  ON_CHANGE_TYPE_QUESTION: 'ON_CHANGE_TYPE_QUESTION',
  ON_CHANGE_TYPE_ANSWER: 'ON_CHANGE_TYPE_ANSWER',
  ON_CLICK_RIGHT_ANSWER: 'ON_CLICK_RIGHT_ANSWER',
  ON_CHANGE_SLUG: 'ON_CHANGE_SLUG',
  ON_CHANGE_CSS: 'ON_CHANGE_CSS',
  ON_CHANGE_JS: 'ON_CHANGE_JS',
  ON_CHANGE_SELECTABLE_LAST_MESSAGE: 'ON_CHANGE_SELECTABLE_LAST_MESSAGE',
  ADD_SELECTABLE_LAST_MESSAGE: 'ADD_SELECTABLE_LAST_MESSAGE',

  // UPDATE
  UPDATE_QUESTION_ORDER: 'UPDATE_QUESTION_ORDER',

  // ADD
  ADD_QUESTION: 'ADD_QUESTION',
  ADD_ANSWER: 'ADD_ANSWER',
  ADD_POLL_TIME: 'ADD_POLL_TIME',
  ADD_ANSWER_AUTO_CHANGE_TIME: 'ADD_ANSWER_AUTO_CHANGE_TIME',
  ADD_ANSWER_TIME: 'ADD_ANSWER_TIME',

  // DELETES
  DELETE_ANSWER: 'DELETE_ANSWER',
  DELETE_QUESTION: 'DELETE_QUESTION',

  // PARTICIPANT FORM
  ADD_PARTICIPANT_ANSWER: 'ADD_PARTICIPANT_ANSWER',
  ADD_PARTICIPANT_NAME: 'ADD_PARTICIPANT_NAME',
  ADD_PARTICIPANT_SURNAME: 'ADD_PARTICIPANT_SURNAME',
  ADD_PARTICIPANT_EMAIL: 'ADD_PARTICIPANT_EMAIL',

};

/*
export const ANSWER_AUTO_CHANGE_TIME = 'ANSWER_AUTO_CHANGE_TIME';
export const ANSWER_TIME = 'ANSWER_TIME';
export const POLL_TIME = 'POLL_TIME';
export const SHOW_TYPE = 'SHOW_TYPE';
export const POLL_ACTIVE = 'POLL_ACTIVE';
export const ANSWER_PERCENT = 'ANSWER_PERCENT';
export const TYPE = 'TYPE';
export const USER_DATA_COLLECT_TYPE = 'USER_DATA_COLLECT_TYPE';

// ONCHANGES
export const ON_CHANGE_NAME = 'ON_CHANGE_NAME';
export const ON_CHANGE_DESC = 'ON_CHANGE_DESC';
export const ON_CHANGE_LAST_DESC = 'ON_CHANGE_LAST_DESC';
export const ON_CHANGE_QUESTION = 'ON_CHANGE_QUESTION';
export const ON_CHANGE_QUESTION_DESC = 'ON_CHANGE_QUESTION_DESC';
export const ON_CHANGE_ANSWER = 'ON_CHANGE_ANSWER';
export const ON_CHANGE_TYPE_QUESTION = 'ON_CHANGE_TYPE_QUESTION';
export const ON_CHANGE_TYPE_ANSWER = 'ON_CHANGE_TYPE_ANSWER';
export const ON_CLICK_RIGHT_ANSWER = 'ON_CLICK_RIGHT_ANSWER';
export const ON_CHANGE_SLUG = 'ON_CHANGE_SLUG';
export const ON_CHANGE_CSS = 'ON_CHANGE_CSS';
export const ON_CHANGE_JS = 'ON_CHANGE_JS';
export const ON_CHANGE_SELECTABLE_LAST_MESSAGE = 'ON_CHANGE_SELECTABLE_LAST_MESSAGE';
export const ADD_SELECTABLE_LAST_MESSAGE = 'ADD_SELECTABLE_LAST_MESSAGE';

// UPDATE
export const UPDATE_QUESTION_ORDER = 'UPDATE_QUESTION_ORDER';

// ADD
export const ADD_QUESTION = 'ADD_QUESTION';
export const ADD_ANSWER = 'ADD_ANSWER';
export const ADD_POLL_TIME = 'ADD_POLL_TIME';
export const ADD_ANSWER_AUTO_CHANGE_TIME = 'ADD_ANSWER_AUTO_CHANGE_TIME';
export const ADD_ANSWER_TIME = 'ADD_ANSWER_TIME';

// DELETES
export const DELETE_ANSWER = 'DELETE_ANSWER';
export const DELETE_QUESTION = 'DELETE_QUESTION';

// PARTICIPANT FORM
export const ADD_PARTICIPANT_ANSWER = 'ADD_PARTICIPANT_ANSWER';
export const ADD_PARTICIPANT_NAME = 'ADD_PARTICIPANT_NAME';
export const ADD_PARTICIPANT_SURNAME = 'ADD_PARTICIPANT_SURNAME';
export const ADD_PARTICIPANT_EMAIL = 'ADD_PARTICIPANT_EMAIL';
*/
