// RADIO BUTTON CHANGE
export default {
  ANSWER_AUTO_CHANGE_TIME: 'ANSWER_AUTO_CHANGE_TIME',

  ANSWER_TIME: 'ANSWER_TIME',
  POLL_TIME: 'POLL_TIME',
  SHOW_TYPE: 'SHOW_TYPE',
  POLL_ACTIVE: 'POLL_ACTIVE',
  ANSWER_PERCENT: 'ANSWER_PERCENT',
  TYPE: 'TYPE',
  USER_DATA_COLLECT_TYPE: 'USER_DATA_COLLECT_TYPE',

  // ONCHANGES
  ON_CHANGE_NAME: 'ON_CHANGE_NAME',
  ON_CHANGE_DESC: 'ON_CHANGE_DESC',
  ON_CHANGE_LAST_DESC: 'ON_CHANGE_LAST_DESC',
  ON_CHANGE_QUESTION: 'ON_CHANGE_QUESTION',
  ON_CHANGE_QUESTION_DESC: 'ON_CHANGE_QUESTION_DESC',
  ON_CHANGE_ANSWER: 'ON_CHANGE_ANSWER',
  ON_CHANGE_TYPE_QUESTION: 'ON_CHANGE_TYPE_QUESTION',
  ON_CHANGE_TYPE_ANSWER: 'ON_CHANGE_TYPE_ANSWER',
  ON_CHANGE_RIGHT_ANSWER: 'ON_CHANGE_RIGHT_ANSWER',
  ON_CHANGE_CSS: 'ON_CHANGE_CSS',
  ON_CHANGE_JS: 'ON_CHANGE_JS',
  RE_ORDER_QUESTION: 'RE_ORDER_QUESTION',
  RE_ORDER_ANSWER: 'RE_ORDER_ANSWER',
  ON_CHANGE_SELECTABLE_LAST_MESSAGE: 'ON_CHANGE_SELECTABLE_LAST_MESSAGE',
  ADD_SELECTABLE_LAST_MESSAGE: 'ADD_SELECTABLE_LAST_MESSAGE',

  // ADD
  ADD_QUESTION: 'ADD_QUESTION',
  ADD_ANSWER: 'ADD_ANSWER',
  ADD_POLL_TIME: 'ADD_POLL_TIME',
  ADD_ANSWER_AUTO_CHANGE_TIME: 'ADD_ANSWER_AUTO_CHANGE_TIME',
  ADD_ANSWER_TIME: 'ADD_ANSWER_TIME',

  // DELETES
  DELETE_ANSWER: 'DELETE_ANSWER',
  DELETE_QUESTION: 'DELETE_QUESTION',

  // PARTICIPANT FORM
  ADD_PARTICIPANT_ANSWER: 'ADD_PARTICIPANT_ANSWER',
  ADD_PARTICIPANT_NAME: 'ADD_PARTICIPANT_NAME',
  ADD_PARTICIPANT_SURNAME: 'ADD_PARTICIPANT_SURNAME',
  ADD_PARTICIPANT_EMAIL: 'ADD_PARTICIPANT_EMAIL',

  GET_PREVIEW_POLL: 'GET_PREVIEW_POLL',
};
